# Notes on different MIMIC-IV preprocessing approaches

With PyHealth we are making a subset of the whole patients (at least, it seems to be), here instead we prefer to focus more on the data, trying to understand all the info contained.

## Description of text-summary data preprocessing in preprocessiong_no_pyhealth.ipynb

This Python script processes clinical data from the MIMIC-IV database to generate structured clinical histories for patients. The data includes patient demographics, hospital admissions, ICU stays, diagnoses, prescriptions, and procedures. The script performs the following key steps:

1. **Loading Data:** Load various datasets representing different aspects of patient information, such as demographics, hospital admissions, ICU stays, prescriptions, and medical procedures.

2. **Mapping ICD Codes to Descriptions:** Merge diagnoses and procedures with their respective ICD code descriptions to provide a more comprehensive understanding of patient records.

3. **Computing Age at Events:** Calculate the age of patients at the time of different medical events such as hospital admissions, ICU stays, and prescriptions. This step includes calculating the age at death for deceased patients.

4. **Generating Structured Clinical History:** For each patient, compile a structured clinical history that includes details about admissions, diagnoses, procedures, prescribed medications, and ICU stays. The script also determines the patient's age and records any deceased status.

5. **Generating and Saving Summaries:** Create clinical history summaries for each patient and save them to a file for further analysis or reporting.

### Detailed Documentation

#### Step 1: Load Data

- Import necessary libraries and load datasets using `pandas.read_csv` to read from CSV files.
- The datasets include:
  - `patients`: Demographic information.
  - `admissions`: Hospital admission records.
  - `icustays`: ICU stay records.
  - `diagnoses`: ICD codes for patient diagnoses.
  - `prescriptions`: Medications administered to patients.
  - `procedures`: ICD codes for medical procedures.
  - `icd_diagnoses`, `icd_procedures`: Descriptions of ICD codes for diagnoses and procedures respectively.
- Convert ICU stay timestamps ('intime' and 'outtime') to `datetime` format for further processing.

#### Step 2: Map ICD Codes to Descriptions

- Merge diagnosis and procedure data with their respective ICD descriptions using a left join (`merge`) on `icd_code` and `icd_version` to add informative descriptions to the datasets.
- Handle missing descriptions by filling them with "Unknown diagnosis" or "Unknown procedure".
- Retain only necessary columns for further analysis:
    * diagnosis: `['subject_id', 'hadm_id', 'icd_version', 'diagnosis_description', 'icd_code']`
    * procedures: `['subject_id', 'hadm_id', 'icd_version', 'procedure_description', 'icd_code']`

#### Step 3: Compute Age at Events

- Filter patient data to retain only relevant i.e. `subject_id`, `gender`, `anchor_age`, `anchor_year`, `dod`.
- Merge patient demographic data with other datasets (admissions, ICU stays, diagnoses, procedures, prescriptions) to include age information.
- Convert relevant date fields (`admittime`, `intime`, and `starttime`) to `datetime` objects.
- Calculate patient age at event time using the auxiliary function `compute_age_at_event`, which adapts age calculations to each type of event's timestamp.
- Directly assign age for events (diagnoses and procedures) lacking precise timestamps.

#### Step 4: Generate Structured Clinical History

- Define the function `generate_patient_history` to compile clinical histories for individual patients.
- For each patient, include gender, death status, and age at death if applicable.
- Sort and iterate through patient hospitalizations, providing details such as:
  - Admission type (*emergency* or *normal*) and discharge status.
  - Diagnoses and procedures associated with each hospitalization.
  - Medications prescribed, detailing dosage and administration route.
  - Summary of ICU stays with length of stay, handling missing discharge dates (if missing we do not compute the icu stay length) to maintain informational integrity.

#### Step 5: Generate and Save Summaries

- Compile summaries for a selection of patients (restrained to 100 for testing) TODO: FOR ALL.
- Utilize a dictionary comprehension to generate and store histories in `summaries`.
- Save all clinical histories to a text file (`clinical_histories.txt`) for external review and use.


## Description of tabular-summary data preprocessing in preprocessiong_no_pyhealth.ipynb

This Python script processes clinical data from the MIMIC-IV database to generate a tabular dataset from textual patient history. It compiles key clinical features like admissions, diagnoses, procedures, ICU stays, and prescriptions into a structured format suitable for machine learning and analysis.

### Detailed Documentation

#### Step 1: Load Data

- Imports necessary libraries and loads datasets.
- Datasets include demographics (`patients`), admissions (`admissions`), ICU stays (`icustays`), medical records (`diagnoses`, `procedures`), and medication prescriptions (`prescriptions`).
- Descriptions for ICD codes are loaded to provide context to diagnoses and procedures.

#### Step 2: Map ICD Codes to Descriptions

- Merges diagnosis and procedure data with descriptions using a left merge on `icd_code` and `icd_version`.
- Ensures the inclusion of a human-readable description of diagnoses and procedures within patient records.

#### Step 3: Compute Age at Events & Mortality

- Filters patient data to retain core columns including `subject_id`, `gender`, `anchor_age`, etc.
- Merges demographic data with main tables to incorporate patient age and mortality status.
- Calculations:
  - `age_at_event` for hospital admissions and prescriptions.
  - Mortality indicators `death_flag` and `age_at_death`.

#### Step 4: Build Tabular Dataset

- Aggregates key features:
  - **ICU Stays**: Counts ICU admissions and calculates total stay days per hospitalization.
  - **Diagnoses**: Summarizes the number and descriptions of diagnoses per hospitalization.
  - **Procedures**: Counts and lists unique procedures performed.
  - **Medications**: Counts and lists prescribed drugs.
- Merges aggregated summaries with core admission features for a comprehensive dataset.
- Handles missing values by filling numerical with zeros and textual lists with "None".

#### Step 5: Save & Display Dataset

- Saves the compiled tabular dataset to a CSV file: `mimiciv_clinical_dataset_tabular.csv`.
- Prepares the dataset for further exploration or machine learning analysis, offering a concise view of patient histories in a structured, numerical format.

In [8]:
import pandas as pd
tabular_data = pd.read_csv("mimiciv_clinical_dataset_tabular.csv")
tabular_data.head(10)

,subject_id,hadm_id,age_at_event,gender,admission_type,discharge_location,death_flag,age_at_death,icu_admissions,icu_days,num_diagnoses,diagnosis_list,num_procedures,procedure_list,num_medications,medication_list
0,10000032,22595853,52,F,URGENT,HOME,1,52.0,0.0,0.0,8.0,"['Portal hypertension', 'Other ascites', 'Cirr...",1.0,['Percutaneous abdominal drainage'],14.0,"['Furosemide', 'Ipratropium Bromide Neb', 'Pot..."
1,10000032,22841357,52,F,EW EMER.,HOME,1,52.0,0.0,0.0,8.0,['Unspecified viral hepatitis C with hepatic c...,1.0,['Percutaneous abdominal drainage'],15.0,"['Furosemide', 'Rifaximin', 'Sodium Chloride 0..."
2,10000032,25742920,52,F,EW EMER.,HOSPICE,1,52.0,0.0,0.0,10.0,['Chronic hepatitis C without mention of hepat...,1.0,['Percutaneous abdominal drainage'],28.0,"['Sodium Chloride 0.9% Flush', '0.9% Sodium C..."
3,10000032,29079034,52,F,EW EMER.,HOME,1,52.0,1.0,0.0,13.0,"['Other iatrogenic hypotension', 'Chronic hepa...",0.0,None,24.0,"['Bisacodyl', 'Senna', 'Calcium Carbonate', 'R..."
4,10000068,25022803,19,F,EU OBSERVATION,NaN,0,NaN,0.0,0.0,1.0,"['Alcohol abuse, unspecified']",1.0,['Other nonoperative respiratory measurements'],0.0,None
5,10000084,23052089,72,M,EW EMER.,HOME HEALTH CARE,1,73.0,0.0,0.0,6.0,"['Neurocognitive disorder with Lewy bodies', '...",0.0,None,13.0,"['Pramipexole', 'Pravastatin', 'rivastigmine',..."
6,10000084,29888819,72,M,EU OBSERVATION,NaN,1,73.0,0.0,0.0,6.0,"['Altered mental status, unspecified', ""Parkin...",0.0,None,0.0,None
7,10000108,27250926,25,M,EU OBSERVATION,NaN,0,NaN,0.0,0.0,2.0,['Cellulitis and abscess of oral soft tissues'...,0.0,None,0.0,None
8,10000117,22927623,55,F,EU OBSERVATION,NaN,0,NaN,0.0,0.0,9.0,"['Dysphagia, unspecified', 'Other specified sy...",0.0,None,2.0,"['Heparin', 'Sodium Chloride 0.9% Flush']"
9,10000117,27988844,57,F,OBSERVATION ADMIT,HOME HEALTH CARE,0,NaN,0.0,0.0,13.0,['Unspecified intracapsular fracture of left f...,1.0,['Reposition Left Upper Femur with Internal Fi...,27.0,"['Iso-Osmotic Dextrose', 'CeFAZolin', 'Vitamin..."

### Considerations:
In this setting we are still missing some key feature with a lot of potential:
* How to use the `labevents` dataset of the `hosp` module?
* `pharmacy` dataset, should also be included? In my opinon no (all the 'important' info are contained already in the prescriptions), but say why.
* Other ICU modules, like `chartevents` (Contains the majority of information documented in the ICU) and `datetimeevents`.
* Is missing the info related to the days between each visit for each patients. This information could be useful for considering the readmission event (we could to model this rather than mortality)
* Is missing a variable which says if the patients died in the visit or not (i.e. lack of mortality definition). To this end the variable `death_flag` is not very clear on what represents (yes, if the patients died, but not specified exactly when - at least in term of visit)

Then, a great open question remains to understand how the data in this format could been use to train standard ML models (LG, RF, Boosting, etc.), profiding example on how other studies performed this (like https://clinicalbench.github.io).

Now, for the latter two open points we created an updated version of that dataset, called `mimiciv_clinical_dataset_tabular_death_visit.csv`. Let us see here a small fraction of the dataset:

In [4]:
tabular_data_refined = pd.read_csv("mimiciv_clinical_dataset_tabular_death_visit.csv")
tabular_data_refined.head(5)

,subject_id,hadm_id,age_at_event,gender,admission_type,admission_category,discharge_location,death_flag,age_at_death,died_during_visit,days_from_last_visit_to_death,days_until_next_visit,icu_admissions,icu_days,num_diagnoses,diagnosis_list,num_procedures,procedure_list,num_medications,medication_list
0,10000032,22595853,52,F,URGENT,EMERGENCY,HOME,1,52.0,0,32.0,50.0,0.0,0.0,8.0,"['Portal hypertension', 'Other ascites', 'Cirr...",1.0,['Percutaneous abdominal drainage'],14.0,"['Furosemide', 'Ipratropium Bromide Neb', 'Pot..."
1,10000032,22841357,52,F,EW EMER.,EMERGENCY,HOME,1,52.0,0,32.0,25.0,0.0,0.0,8.0,['Unspecified viral hepatitis C with hepatic c...,1.0,['Percutaneous abdominal drainage'],15.0,"['Furosemide', 'Rifaximin', 'Sodium Chloride 0..."
2,10000032,29079034,52,F,EW EMER.,EMERGENCY,HOME,1,52.0,0,32.0,11.0,1.0,0.0,13.0,"['Other iatrogenic hypotension', 'Chronic hepa...",0.0,None,24.0,"['Bisacodyl', 'Senna', 'Calcium Carbonate', 'R..."
3,10000032,25742920,52,F,EW EMER.,EMERGENCY,HOSPICE,1,52.0,0,32.0,-1.0,0.0,0.0,10.0,['Chronic hepatitis C without mention of hepat...,1.0,['Percutaneous abdominal drainage'],28.0,"['Sodium Chloride 0.9% Flush', '0.9% Sodium C..."
4,10000068,25022803,19,F,EU OBSERVATION,NORMAL,NaN,0,NaN,0,NaN,-1.0,0.0,0.0,1.0,"['Alcohol abuse, unspecified']",1.0,['Other nonoperative respiratory measurements'],0.0,None

As we can see here we have more useful variables than in the previous version of the dataset. In particular, we have the following:
* `admission_category`: we simplify the 9-categories `admission_type` variable in 2-categories variable, where we grouped toghether emergency-values and we set as "normal" the others.
* `died_during_visit`: this variable tells us whether the patients died during the hospitalization or not. If not, we keep track on how many days after the last hospitalization the patient died.
* `days_from_last_visit_to_death`: this variable tells us (if the patient died outside an hospitalization) after how many days from last visit the patient died. **NOTE: If the patient died after one year from the last visit, then it's not reported. That's from how MIMIC-IV data is built.**
* `days_until_next_visit`: this variable tells us how many days we have from one visit to the next one, for each patient. If the patient has only one visit, we then have -1 as a value.

Now, we should focus on one aspect, let us see how many unique individuals we have in this dataset:

In [5]:
len(tabular_data_refined['subject_id'].unique())

223452

In the documentation of MIMIC, however, we have:
_As of MIMIC-IV v3.0 there are 364,627 unique patients, of whom 223,452 had at least one hospitalization (i.e. at least one record in the admissions table). The remaining 141,175 patients were only seen in the emergency department, which can be verified using the transfers table._

So, we have 141175 patients who are in the ICU department but not in the hospitalization. We should investigate further how we should consider these patients for example: 
* do they have as well some dod information?
* is it possible to have different ICU admission for the same individual?

In [7]:
import pandas as pd

# Load necessary MIMIC-IV tables
patients = pd.read_csv("/root/MIMICIV/data/mimic-iv-3.1/hosp/patients.csv")      # Contains subject_id, dod
admissions = pd.read_csv("/root/MIMICIV/data/mimic-iv-3.1/hosp/admissions.csv")  # Contains subject_id, hadm_id
transfers = pd.read_csv("/root/MIMICIV/data/mimic-iv-3.1/hosp/transfers.csv.gz", compression="gzip")    # Contains subject_id, eventtype
icustays = pd.read_csv("/root/MIMICIV/data/mimic-iv-3.1/icu/icustays.csv")       # Contains subject_id, hadm_id, stay_id

# 1. Identify ED-only patients
# Patients in transfers but NOT in admissions
ed_only_patients = set(transfers["subject_id"]) - set(admissions["subject_id"])
ed_only_df = transfers[transfers["subject_id"].isin(ed_only_patients)]

# 2. Check how many ED-only patients have a recorded date of death
ed_only_with_dod = patients[patients["subject_id"].isin(ed_only_patients) & patients["dod"].notna()]
print(f"Number of ED-only patients: {len(ed_only_patients)}")
print(f"ED-only patients with recorded DOD: {len(ed_only_with_dod)}")

# 3. Check for multiple ICU stays per patient
icustay_counts = icustays.groupby("subject_id")["stay_id"].count().reset_index()
multiple_icu_stays = icustay_counts[icustay_counts["stay_id"] > 1]
print(f"Number of patients with multiple ICU stays: {len(multiple_icu_stays)}")

# Show ICU stays for ED-only patients
ed_only_icu_stays = icustays[icustays["subject_id"].isin(ed_only_patients)]
print(f"Number of ED-only patients with ICU stays: {len(ed_only_icu_stays['subject_id'].unique())}")

# Display results in a DataFrame
results_df = pd.DataFrame({
    "Total ED-Only Patients": [len(ed_only_patients)],
    "ED-Only Patients with DOD": [len(ed_only_with_dod)],
    "Patients with Multiple ICU Stays": [len(multiple_icu_stays)],
    "ED-Only Patients with ICU Stays": [len(ed_only_icu_stays['subject_id'].unique())]
})

# Display DataFrame
print("\nSummary of MIMIC-IV Analysis:")
display(results_df)

Number of ED-only patients: 141175
ED-only patients with recorded DOD: 1419
Number of patients with multiple ICU stays: 16242
Number of ED-only patients with ICU stays: 0

Summary of MIMIC-IV Analysis:

,Total ED-Only Patients,ED-Only Patients with DOD,Patients with Multiple ICU Stays,ED-Only Patients with ICU Stays
0,141175,1419,16242,0

It could be that  these patients does have a record in the `patients` file but not in the `admissions` one (or in other file).

In [9]:
# 2. Check if these patients exist in patients.csv
ed_only_in_patients = patients[patients["subject_id"].isin(ed_only_patients)]

# 3. Count how many ED-only patients exist in patients.csv
num_ed_only_in_patients = len(ed_only_in_patients)
num_ed_only_missing = len(ed_only_patients) - num_ed_only_in_patients

print(f"Total ED-only patients: {len(ed_only_patients)}")
print(f"ED-only patients found in patients.csv: {num_ed_only_in_patients}")
print(f"ED-only patients missing from patients.csv: {num_ed_only_missing}")

# Display results in a DataFrame
results_df = pd.DataFrame({
    "Total ED-Only Patients": [len(ed_only_patients)],
    "ED-Only Patients in patients.csv": [num_ed_only_in_patients],
    "ED-Only Patients Missing in patients.csv": [num_ed_only_missing]
})

# Show DataFrame
display(results_df)

Total ED-only patients: 141175
ED-only patients found in patients.csv: 141175
ED-only patients missing from patients.csv: 0

,Total ED-Only Patients,ED-Only Patients in patients.csv,ED-Only Patients Missing in patients.csv
0,141175,141175,0

Okay, so, we have all the patients information in the patients.csv file (where we have also all the dod info).
There are patients registered in the `patients.csv` file but that are missing from the hosp module or icu module. For these patients we could investigate whom they are, but we can do as well nothing since they could be related to other things. However we should carefully check whether there are some patients in the **ED** unit that are not in the ICU module.

I downloaded this dataset in `edstays.csv` from https://physionet.org/content/mimic-iv-ed/2.2/ed/#files-panel and I placed in the `data/` folder so it's in the `.gitignore` file.

We can now proceed with this check.

In [ ]:
import pandas as pd

# Load necessary MIMIC-IV tables
edstays = pd.read_csv("/root/MIMICIV/data/mimic-iv-3.1/edstays.csv")  # Contains ED patients
admissions = pd.read_csv("/root/MIMICIV/data/mimic-iv-3.1/hosp/admissions.csv")  # Contains hospital admissions
icustays = pd.read_csv("/root/MIMICIV/data/mimic-iv-3.1/icu/icustays.csv")  # Contains ICU stays

# 1. Identify all unique ED patients
ed_patients = set(edstays["subject_id"])

# 2. Find ED patients who were NEVER admitted to the hospital
ed_not_admitted = ed_patients - set(admissions["subject_id"])

# 3. Find ED patients who were NEVER admitted to the ICU
ed_not_in_icu = ed_patients - set(icustays["subject_id"])

# 4. Count how many ED patients were in neither ICU nor Hospital
#ed_only_patients = ed_not_admitted & ed_not_in_icu
ed_only_patients = ed_not_admitted.intersection(ed_not_in_icu)

# Display results
print(f"Total patients in ED module: {len(ed_patients)}")
print(f"ED patients NOT admitted to hospital: {len(ed_not_admitted)}")
print(f"ED patients NOT admitted to ICU: {len(ed_not_in_icu)}")
print(f"ED patients in neither Hospital nor ICU (ED-only): {len(ed_only_patients)}")

# Create a DataFrame for results
results_df = pd.DataFrame({
    "Total ED Patients": [len(ed_patients)],
    "ED Patients NOT Admitted to Hospital": [len(ed_not_admitted)],
    "ED Patients NOT Admitted to ICU": [len(ed_not_in_icu)],
    "ED-Only Patients (Neither Hospital nor ICU)": [len(ed_only_patients)]
})

# Display DataFrame
display(results_df)

Total patients in ED module: 205504
ED patients NOT admitted to hospital: 79409
ED patients NOT admitted to ICU: 171811
ED patients in neither Hospital nor ICU (ED-only): 79409

,Total ED Patients,ED Patients NOT Admitted to Hospital,ED Patients NOT Admitted to ICU,ED-Only Patients (Neither Hospital nor ICU)
0,205504,79409,171811,79409

In [13]:
# 2. Find ED patients who were admitted to the hospital
ed_admitted_to_hospital = ed_patients.intersection(set(admissions["subject_id"]))

# 3. Find ED patients who were admitted to the ICU
ed_admitted_to_icu = ed_patients.intersection(set(icustays["subject_id"]))

# 4. Find ED patients who were admitted to the hospital but NOT the ICU
ed_hospital_not_icu = ed_admitted_to_hospital - ed_admitted_to_icu

# Display results
print(f"Total ED Patients: {len(ed_patients)}")
print(f"ED Patients Admitted to Hospital: {len(ed_admitted_to_hospital)}")
print(f"ED Patients Admitted to ICU: {len(ed_admitted_to_icu)}")
print(f"ED Patients Admitted to Hospital but NOT ICU: {len(ed_hospital_not_icu)}")

# Create DataFrame for results
results_df = pd.DataFrame({
    "Total ED Patients": [len(ed_patients)],
    "ED Patients Admitted to Hospital": [len(ed_admitted_to_hospital)],
    "ED Patients Admitted to ICU": [len(ed_admitted_to_icu)],
    "ED Patients Admitted to Hospital but NOT ICU": [len(ed_hospital_not_icu)]
})

# Show DataFrame
display(results_df)

Total ED Patients: 205504
ED Patients Admitted to Hospital: 126095
ED Patients Admitted to ICU: 33693
ED Patients Admitted to Hospital but NOT ICU: 92402

,Total ED Patients,ED Patients Admitted to Hospital,ED Patients Admitted to ICU,ED Patients Admitted to Hospital but NOT ICU
0,205504,126095,33693,92402

In [14]:
# great. If we substract from the 171811 patients not admitted to ICU the 92402 (ED Patients Admitted to Hospital but NOT ICU) we get:
len(ed_not_in_icu) - len(ed_hospital_not_icu)

79409

Which is exactly the number of ED-Only Patients (Neither Hospital nor ICU).

Now, of these 79409 patients, are there any emergency?

In [15]:
ed_only_patients

{17301508,
 16252935,
 12058642,
 19136531,
 19922962,
 14417948,
 10747933,
 19398689,
 19922978,
 13369377,
 18087973,
 15990823,
 11272232,
 14417960,
 17563689,
 16252973,
 13107247,
 18350131,
 15466553,
 10485818,
 19660857,
 13893693,
 19136574,
 18874431,
 10223689,
 14417994,
 18874461,
 11534429,
 12320862,
 11272290,
 12058728,
 13107306,
 18088045,
 11534447,
 13369457,
 13107314,
 18088049,
 11272313,
 18350202,
 18874492,
 19660925,
 17825919,
 14680193,
 19136646,
 15466635,
 17825939,
 13107350,
 12583064,
 17039513,
 19923102,
 14155935,
 12583076,
 16253095,
 16777383,
 17301671,
 12320940,
 13369516,
 17563823,
 16777394,
 14155959,
 17301692,
 13893825,
 15466701,
 10223823,
 19136720,
 10748130,
 11534563,
 13107427,
 15728874,
 12845291,
 13893867,
 13369581,
 16777454,
 15728880,
 10223856,
 10748153,
 15466746,
 18088202,
 14418189,
 15991061,
 19661080,
 11272474,
 12845339,
 15728927,
 15204642,
 18612515,
 16777508,
 18088228,
 19136805,
 15204651,
 10223915,
 15204655,
 11534641,
 17826105,
 11534651,
 18874685,
 17301838,
 14156111,
 17563982,
 19923281,
 14942550,
 15991126,
 10486106,
 18874714,
 19923290,
 14680413,
 18612572,
 17039717,
 13107558,
 15204710,
 12583272,
 10486123,
 13107563,
 17301871,
 11534706,
 11010423,
 12845439,
 16253319,
 13107597,
 15729049,
 19399065,
 13369755,
 11796892,
 11534759,
 17301932,
 14680497,
 19661238,
 15466940,
 10748353,
 17301954,
 14418371,
 16515522,
 11272647,
 14680526,
 13631957,
 18612693,
 10748382,
 10224095,
 11010531,
 19399143,
 12059123,
 12321271,
 15991291,
 13894140,
 19923454,
 13107714,
 13632010,
 10224138,
 12845581,
 18874899,
 18350612,
 14680600,
 19399192,
 17826333,
 13107746,
 15204899,
 12845607,
 15204905,
 14156333,
 14942768,
 14418483,
 11010616,
 11534907,
 15991357,
 10486343,
 11010633,
 13369931,
 10486349,
 17826385,
 13894227,
 15467092,
 17564249,
 19399258,
 19923548,
 14156381,
 17564252,
 11534946,
 17039978,
 14942829,
 10486383,
 12321391,
 19661423,
 16515702,
 11534967,
 17039995,
 14156413,
 12321405,
 14418557,
 10224256,
 12321414,
 10486407,
 15729289,
 10224269,
 18612882,
 16253590,
 17302167,
 12845718,
 16777881,
 16515737,
 13107874,
 11010727,
 13107879,
 13370026,
 19923627,
 13894315,
 10224301,
 11535022,
 11535024,
 19137216,
 14680770,
 17826498,
 11272898,
 14942915,
 16253641,
 10748618,
 16253643,
 19399371,
 18875085,
 17040077,
 17564377,
 16777956,
 15205100,
 10486509,
 14418671,
 13370100,
 10486517,
 17826553,
 19399417,
 18088697,
 10486528,
 11535104,
 10748672,
 15991553,
 11010827,
 15991570,
 18875161,
 19923740,
 14156574,
 19137313,
 19923746,
 10224418,
 13370146,
 14943010,
 12583719,
 13108019,
 17302326,
 17302327,
 10748730,
 15467324,
 14680907,
 15205205,
 11797335,
 15205208,
 14156636,
 11010912,
 16253795,
 15729512,
 11010922,
 11273071,
 18613114,
 11273084,
 13632381,
 12583810,
 11535239,
 17826703,
 18088848,
 11797395,
 17826710,
 18875291,
 13108124,
 18613149,
 16778147,
 14681004,
 11273136,
 12059570,
 11273140,
 12583862,
 14943168,
 19137473,
 15205314,
 15991747,
 13370310,
 19661766,
 15729609,
 18875340,
 19399628,
 14418897,
 17040338,
 13108180,
 10224596,
 19923930,
 16516062,
 12583904,
 14681057,
 18088928,
 13632487,
 15729641,
 10748915,
 11797492,
 11535349,
 17826809,
 11273212,
 15729667,
 12059653,
 16778249,
 19399692,
 12059663,
 13108250,
 10224669,
 13108259,
 18089006,
 18875444,
 19661876,
 18351161,
 16516158,
 15467590,
 12584007,
 18613319,
 16254025,
 14419020,
 15991892,
 18613333,
 19661909,
 11273305,
 12321887,
 19399777,
 17564769,
 12846178,
 19399782,
 19661937,
 13894771,
 12321916,
 16778367,
 15467649,
 19399810,
 17826949,
 12584070,
 18613391,
 16516248,
 13370527,
 19661986,
 15991971,
 10224805,
 16254124,
 10224813,
 14943406,
 15205557,
 11535542,
 17040575,
 14156992,
 13370565,
 18613450,
 13632715,
 16254157,
 12846293,
 19137749,
 12846295,
 12584157,
 18351325,
 15729889,
 10487015,
 14419175,
 18089193,
 19924219,
 17564923,
 14419197,
 11273472,
 17564928,
 14943491,
 11011334,
 12846343,
 12059912,
 12059929,
 12584217,
 13370653,
 19137825,
 10487083,
 14681387,
 10487088,
 14157106,
 15729975,
 18875708,
 13632829,
 12059966,
 12322110,
 17564991,
 18613572,
 19662153,
 14157130,
 14157131,
 12059982,
 11273561,
 11273563,
 10224988,
 10749277,
 15205729,
 14419300,
 12584294,
 10224998,
 14419303,
 19662186,
 17827182,
 14943599,
 12584306,
 15205747,
 19400051,
 19400052,
 17040754,
 11797875,
 11273597,
 16778622,
 14943621,
 18875783,
 19662220,
 15205773,
 14943630,
 10487188,
 15467931,
 15992219,
 13370781,
 18613664,
 18613669,
 17302951,
 13895085,
 13632944,
 16778673,
 15730100,
 12322235,
 19137979,
 12060105,
 17565130,
 13108685,
 13108686,
 18875863,
 10225127,
 14943722,
 19924459,
 14157293,
 12584446,
 13108739,
 10487300,
 18875907,
 17303046,
 10749443,
 19662344,
 17565195,
 14681614,
 13633042,
 16516627,
 17827349,
 15205916,
 18089500,
 19400230,
 16254504,
 11273772,
 18351662,
 12060210,
 11535923,
 11011636,
 16778805,
 15205942,
 17827379,
 14157368,
 14157370,
 16254522,
 17827388,
 18351695,
 10487392,
 13633124,
 17827432,
 18613866,
 10749549,
 10487408,
 18351728,
 19924594,
 16516725,
 12584574,
 19662470,
 17041031,
 12846732,
 14419600,
 16516756,
 17303191,
 15468185,
 18876058,
 11011750,
 15206057,
 17303212,
 18089645,
 19138225,
 19400370,
 17303223,
 17827516,
 10749630,
 11011776,
 13371072,
 13895362,
 16516803,
 11536070,
 15730377,
 14157517,
 15992539,
 17565410,
 11011811,
 14681848,
 13108985,
 12060414,
 17041154,
 15206153,
 19924748,
 15992588,
 17827601,
 15206168,
 12584732,
 15206175,
 14681888,
 15206179,
 14681892,
 13633317,
 15468324,
 18876202,
 16779061,
 12846908,
 17303358,
 17827652,
 13633350,
 18614086,
 12060491,
 12322635,
 18614094,
 12322645,
 13895516,
 17041245,
 19400544,
 18876259,
 14681957,
 12846950,
 12584808,
 18351976,
 19662697,
 18614122,
 19662701,
 18614126,
 11536239,
 11274098,
 17303411,
 14944119,
 17041276,
 13371261,
 18614145,
 13371266,
 11536260,
 11798405,
 10225548,
 14682003,
 17303443,
 13109147,
 16779164,
 17041309,
 14157726,
 18614177,
 11798434,
 10749861,
 15730600,
 12060587,
 17041324,
 13895597,
 10225583,
 13895600,
 16517042,
 19138482,
 15992757,
 13633463,
 10749879,
 18614201,
 17827772,
 10225596,
 16779198,
 14682047,
 19924932,
 10487752,
 16779214,
 18089934,
 10487763,
 14157781,
 16779223,
 15730648,
 14419941,
 11274214,
 15206375,
 10749930,
 12847082,
 18089963,
 17041401,
 14682106,
 16779265,
 14157828,
 16254980,
 12584966,
 11798533,
 19925000,
 12060682,
 17565706,
 11798540,
 19662863,
 17827856,
 14419986,
 15992851,
 18352148,
 12322853,
 14157867,
 12322866,
 17565750,
 14682180,
 12585030,
 19925066,
 18614350,
 13633621,
 13895767,
 12585060,
 17827940,
 13109352,
 19138666,
 12060779,
 16255083,
 13109357,
 11798636,
 11012208,
 14420080,
 18090096,
 17041531,
 14682236,
 17303677,
 17303678,
 16517247,
 19400835,
 17565827,
 11798663,
 15992975,
 12060817,
 10225810,
 10487956,
 12060821,
 11012246,
 15206548,
 11012253,
 10750114,
 14944418,
 11798696,
 13895851,
 13895857,
 14420147,
 18876599,
 12323006,
 19663039,
 15206592,
 13633731,
 15468739,
 16255173,
 14944454,
 19663048,
 12847310,
 12060889,
 14682340,
 11274469,
 12060902,
 17303786,
 11274474,
 12323050,
 19138799,
 15993074,
 13895933,
 19925248,
 15468800,
 11274499,
 14158086,
 12060942,
 17303824,
 16517392,
 19925269,
 11274520,
 13109530,
 14682396,
 11798814,
 19663140,
 19400999,
 13371688,
 18614568,
 10750251,
 13109548,
 15206701,
 12847407,
 18876725,
 12323126,
 18876727,
 10225978,
 11798843,
 14420282,
 18614589,
 11012416,
 19925314,
 14944582,
 19401032,
 16779594,
 16779595,
 14682444,
 13896010,
 13896017,
 18352468,
 13371736,
 10488153,
 10750297,
 16517468,
 11536747,
 10226027,
 11012462,
 15206771,
 18090355,
 10226037,
 17828216,
 16255356,
 16779644,
 10226045,
 18352515,
 11012496,
 17828240,
 16255380,
 12061077,
 16255381,
 17041813,
 12323227,
 17828255,
 15731114,
 11798956,
 13633965,
 14944685,
 12061111,
 11012537,
 11012539,
 15993276,
 19663295,
 17304000,
 12847556,
 11536844,
 19139021,
 12061138,
 15731158,
 17041880,
 17041881,
 11012575,
 10488295,
 16255463,
 13896168,
 11799021,
 12847599,
 10226166,
 14420477,
 13634046,
 12847614,
 12585472,
 19663360,
 10750467,
 14158350,
 18876942,
 11012624,
 11536913,
 10488338,
 10750480,
 13371921,
 10488341,
 14944787,
 14420500,
 19663380,
 13896219,
 19663400,
 12323371,
 11274802,
 11536951,
 14682680,
 19401273,
 11799097,
 14158397,
 12323407,
 17042005,
 15993431,
 13371992,
 17042009,
 18352732,
 17304157,
 14420574,
 11274847,
 14682720,
 16779873,
 17042019,
 17042021,
 13896302,
 14944880,
 12061299,
 17566324,
 11012730,
 15207037,
 12061314,
 10226308,
 18877061,
 11012745,
 14944905,
 14682765,
 14944919,
 18877083,
 10750620,
 18352798,
 13372068,
 13634219,
 11274933,
 19925687,
 17304251,
 16517819,
 11799227,
 15731393,
 17042115,
 11537093,
 19925704,
 13372107,
 18352844,
 12061393,
 10750676,
 15993560,
 11012834,
 12585698,
 13372130,
 14944997,
 16255722,
 13109998,
 14158574,
 11012849,
 18877174,
 17566459,
 12323586,
 12323587,
 17042183,
 18877195,
 12585741,
 16255761,
 11012882,
 17304338,
 14420757,
 14682902,
 10750742,
 12061464,
 19401496,
 13372182,
 12061471,
 10226463,
 16517922,
 13372196,
 19139366,
 18090803,
 15993654,
 18352952,
 13896505,
 16255802,
 15993658,
 10488637,
 16255805,
 13896509,
 15469373,
 11537225,
 11012940,
 10750797,
 10750802,
 18090836,
 12585813,
 11799383,
 19139415,
 13110110,
 15993696,
 19139431,
 17304427,
 12847980,
 13110128,
 18090865,
 10488697,
 18090875,
 18353020,
 17042301,
 15993726,
 17828735,
 11013001,
 12848009,
 14420878,
 13372306,
 10488725,
 14420888,
 19663773,
 10226599,
 14683048,
 10226617,
 11275197,
 16780235,
 12323788,
 14158797,
 12323790,
 19663820,
 15207375,
 10226638,
 11799502,
 16518098,
 15731671,
 16518105,
 12061658,
 12585950,
 12061665,
 12323813,
 19925991,
 12323817,
 15207403,
 13634545,
 18090999,
 16255993,
 14420988,
 14683133,
 19926013,
 15993855,
 17304586,
 12585995,
 17042444,
 16256017,
 15993874,
 19401749,
 15731735,
 11275288,
 12061722,
 10751005,
 17828894,
 14158879,
 13372446,
 10751007,
 15993887,
 16518176,
 15469602,
 17304614,
 14945321,
 19926058,
 11537452,
 14421041,
 10226738,
 11537464,
 14158905,
 12323896,
 11275324,
 15993922,
 16256068,
 16780358,
 16256071,
 14421062,
 16518216,
 11799625,
 17566791,
 15469646,
 11275344,
 19926097,
 15731805,
 18877533,
 18877542,
 19139686,
 16780393,
 11275378,
 17304698,
 11275387,
 13372542,
 11799680,
 10488963,
 12323973,
 14683270,
 16780423,
 13634696,
 19401863,
 16518285,
 19664022,
 17042583,
 19926170,
 13896858,
 13372573,
 13110435,
 17566884,
 18877608,
 14683317,
 15207608,
 14421176,
 11275450,
 11799741,
 16518342,
 14945479,
 19664073,
 15207627,
 18877649,
 18353364,
 15207641,
 15994074,
 18615514,
 ...}